# Generated by Django 4.0.5 on 2022-06-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('autor', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='images')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.genero')),
            ],
        ),
    ]
