# Generated by Django 4.0.5 on 2022-06-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='genero',
        ),
        migrations.AddField(
            model_name='livros',
            name='genero',
            field=models.ManyToManyField(to='livros.genero'),
        ),
    ]
