# Generated by Django 4.0.5 on 2022-06-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_remove_livros_genero_livros_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
